-- 코드를 입력하세요
WITH ORDER_LIST AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05-%'
    GROUP BY PRODUCT_ID
)

SELECT A.PRODUCT_ID, B.PRODUCT_NAME, B.PRICE * A.TOTAL_AMOUNT TOTAL_SALES
FROM ORDER_LIST A, FOOD_PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID